package org.agmas.harpymodloader;

import dev.doctor4t.wathe.api.GameMode;
import dev.doctor4t.wathe.api.Faction;
import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheGameModes;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.GameFunctions;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.ArgumentTypeRegistry;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.fabricmc.loader.impl.util.log.Log;
import net.fabricmc.loader.impl.util.log.LogCategory;
import net.minecraft.command.argument.serialize.ConstantArgumentSerializer;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.text.MutableText;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;

import net.minecraft.util.Language;
import org.agmas.harpymodloader.commands.ForceModifierCommand;
import org.agmas.harpymodloader.commands.ForceRoleCommand;
import org.agmas.harpymodloader.commands.ListRolesCommand;
import org.agmas.harpymodloader.commands.RoleWeightsCommand;
import org.agmas.harpymodloader.commands.SetEnabledModifierCommand;
import org.agmas.harpymodloader.commands.SetEnabledRoleCommand;
import org.agmas.harpymodloader.commands.SetRoleCommand;
import org.agmas.harpymodloader.commands.argument.ModifierArgumentType;
import org.agmas.harpymodloader.commands.argument.RoleArgumentType;
import org.agmas.harpymodloader.config.HarpyModLoaderConfig;
import org.agmas.harpymodloader.modded_murder.ModdedMurderGameMode;
import org.agmas.harpymodloader.modifiers.HMLModifiers;
import org.agmas.harpymodloader.modifiers.Modifier;

public class Harpymodloader implements ModInitializer {

    public static HashMap<Identifier, Integer> ROLE_MAX = new HashMap<>();
    public static HashMap<Identifier, Integer> MODIFIER_MAX = new HashMap<>();

    public static HashMap<Role, List<UUID>> FORCED_MODDED_ROLE = new HashMap<>();
    public static HashMap<UUID, Role> FORCED_MODDED_ROLE_FLIP = new HashMap<>();

    public static HashMap<Modifier, List<UUID>> FORCED_MODDED_MODIFIER = new HashMap<>();

    public static ArrayList<Role> VANNILA_ROLES = new ArrayList<>();
    public static ArrayList<Role> SPECIAL_ROLES = new ArrayList<>();
    public static ArrayList<Role> OVERWRITE_ROLES = new ArrayList<>();
    public static String MOD_ID = "harpymodloader";

    public static GameMode MODDED_GAMEMODE;
    public static boolean wantsToStartVannila = false;

    public static HashMap<Role, RoleAnnouncementTexts.RoleAnnouncementText> autogeneratedAnnouncements = new HashMap<>();
    public static HashMap<RoleAnnouncementTexts.RoleAnnouncementText, Role> autogeneratedAnnouncements_flip = new HashMap<>();

    @Override
    public void onInitialize() {
        HarpyModLoaderConfig.HANDLER.load();
        VANNILA_ROLES.add(WatheRoles.LOOSE_END);
        VANNILA_ROLES.add(WatheRoles.CIVILIAN);
        VANNILA_ROLES.add(WatheRoles.KILLER);
        VANNILA_ROLES.add(WatheRoles.VIGILANTE);
        VANNILA_ROLES.add(WatheRoles.DISCOVERY_CIVILIAN);

        SPECIAL_ROLES.add(WatheRoles.LOOSE_END);
        SPECIAL_ROLES.add(WatheRoles.DISCOVERY_CIVILIAN);
        SPECIAL_ROLES.add(WatheRoles.CIVILIAN); // civilian is considered special since it can't be assigned, just given out to everyone

        OVERWRITE_ROLES.add(WatheRoles.CIVILIAN);
        /*
         * 扩展义警职业需要以“原版义警位”为替换基底，
         * 因此这里也必须把 vanilla vigilante 视为可覆写角色。
         *
         * 否则后续像 Better Vigilante 这类职业在替换流程里永远拿不到候选玩家，
         * 表现出来就是：
         * 1. 随机怎么开都刷不出来；
         * 2. forceRole 指到义警阵营职业时，最终也会掉回平民。
         */
        OVERWRITE_ROLES.add(WatheRoles.VIGILANTE);
        OVERWRITE_ROLES.add(WatheRoles.KILLER);

        registerCommands();
        HMLModifiers.init();

        MODDED_GAMEMODE = WatheGameModes.registerGameMode(Identifier.of(MOD_ID, "modded"), new ModdedMurderGameMode(Identifier.of(MOD_ID, "modded")));
        registerStartGameModeResolver();

        ServerLifecycleEvents.SERVER_STARTED.register((minecraftServer -> {
            refreshRoles();
        }));
    }

    private static void registerStartGameModeResolver() {
        GameFunctions.registerStartGameModeResolver((world, gameMode) -> {
            /*
             * Harpy 默认会接管 Wathe 的 Murder 开局，把它替换成 modded murder。
             * 这个解析器运行在 Wathe 人数判断和自动开局 HUD 之前，
             * 因此 /wathe:startPlayerCount mode harpymodloader:modded <人数>
             * 才能真正控制 Harpy 玩法的开局人数。
             *
             * 当管理员显式执行 /wathe:start murder ... 时，VannilaStartMixin 会临时设置
             * wantsToStartVannila，此时保持原版 Murder，不做替换。
             */
            if (gameMode == WatheGameModes.MURDER && !wantsToStartVannila) {
                return MODDED_GAMEMODE;
            }
            return gameMode;
        });
        GameFunctions.registerAfterStartGameAttempt(() -> {
            /*
             * wantsToStartVannila 只表达“这一次 /wathe:start murder 想开原版 Murder”。
             * 若本次因为人数不足、投票中或重复开局而没有进入 initializeGame，
             * 也必须在 startGame 结束时清掉，否则后续自动开局会误以为还要保留原版 Murder。
             */
            wantsToStartVannila = false;
        });
    }

    //
    // re-indexes roles
    //
    public static void refreshRoles() {
        for (Role role : WatheRoles.ROLES) {
            if (SPECIAL_ROLES.contains(role)) continue;
            /*
             * 扩展职业权重已经统一由 Wathe scoreboard 账本维护，Harpy 不再创建第二份静态 map。
             * 这里仅用公告反查表判断是否已经注册，避免服务器重载角色时重复插入公告条目。
             */
            if (!autogeneratedAnnouncements.containsKey(role)) {

                boolean useOldKey = !Language.getInstance().hasTranslation("announcement.role." + role.identifier().toTranslationKey()) && Language.getInstance().hasTranslation("announcement.role." + role.identifier().getPath());
                RoleAnnouncementTexts.RoleAnnouncementText roleAnnouncementText = new RoleAnnouncementTexts.RoleAnnouncementText(useOldKey ? role.identifier().getPath() : role.identifier().toTranslationKey(), role.color());
                autogeneratedAnnouncements.put(role, roleAnnouncementText);
                autogeneratedAnnouncements_flip.put(roleAnnouncementText, role);
                RoleAnnouncementTexts.registerRoleAnnouncementText(roleAnnouncementText);
            }
        }
    }

    public static void addToForcedModifiers(Modifier modifier, PlayerEntity player) {
        if (!FORCED_MODDED_MODIFIER.containsKey(modifier)) FORCED_MODDED_MODIFIER.put(modifier, new ArrayList<>());
        /*
         * forceModifier 允许一个玩家被强制多个不同词条，但同一个词条不需要重复记录。
         * 去重可以避免管理员连续点同一条命令后，查询和后续维护看到一堆重复 UUID。
         */
        if (!FORCED_MODDED_MODIFIER.get(modifier).contains(player.getUuid())) {
            FORCED_MODDED_MODIFIER.get(modifier).add(player.getUuid());
        }

    }

    public static void addToForcedRoles(Role role, PlayerEntity player) {
        UUID playerUuid = player.getUuid();
        Role previousRole = FORCED_MODDED_ROLE_FLIP.put(playerUuid, role);
        /*
         * 一个玩家同一局只能被强制成一个职业。
         * 旧逻辑只更新了 uuid -> role 的反查表，却没有从旧 role -> uuid 列表里移除玩家；
         * 管理员如果先后执行两次 /forceRole，开局替换阶段就可能同时把玩家当成两个强制职业候选。
         */
        if (previousRole != null && previousRole != role && FORCED_MODDED_ROLE.containsKey(previousRole)) {
            FORCED_MODDED_ROLE.get(previousRole).remove(playerUuid);
            if (FORCED_MODDED_ROLE.get(previousRole).isEmpty()) {
                FORCED_MODDED_ROLE.remove(previousRole);
            }
        }

        if (!FORCED_MODDED_ROLE.containsKey(role)) FORCED_MODDED_ROLE.put(role, new ArrayList<>());
        if (!FORCED_MODDED_ROLE.get(role).contains(playerUuid)) {
            FORCED_MODDED_ROLE.get(role).add(playerUuid);
        }
    }

    public static void setRoleMaximum(Identifier role, Integer max) {
        ROLE_MAX.put(role, max);
    }

    public static void setRoleMaximum(Role role, Integer max) {
        setRoleMaximum(role.identifier(), max);
    }

    /**
     * 判断某个职业是否属于指定阵营。
     *
     * <p>HarpyModLoader 过去很多地方仍在使用
     * {@code isInnocent()} / {@code canUseKiller()} 这套旧语义做角色池划分。
     * 这里补一个统一入口后，扩展职业只要显式注册了阵营，
     * 后续分配逻辑就可以稳定按阵营工作。</p>
     */
    public static boolean isFaction(Role role, Faction faction) {
        return role != null && role.getFaction() == faction;
    }

    public void registerCommands() {
        ArgumentTypeRegistry.registerArgumentType(
                Identifier.of(MOD_ID, "role"),
                RoleArgumentType.class,
                new RoleArgumentType.Serializer()
        );
        ArgumentTypeRegistry.registerArgumentType(
                Identifier.of(MOD_ID, "modifier"),
                ModifierArgumentType.class,
                ConstantArgumentSerializer.of(ModifierArgumentType::create)
        );

        CommandRegistrationCallback.EVENT.register((dispatcher, registryAccess, environment) -> {
            ForceRoleCommand.register(dispatcher);
            SetRoleCommand.register(dispatcher);
            RoleWeightsCommand.register(dispatcher);
            SetEnabledRoleCommand.register(dispatcher);
            ListRolesCommand.register(dispatcher);
            ForceModifierCommand.register(dispatcher);
            SetEnabledModifierCommand.register(dispatcher);
        });
    }

    public static MutableText getRoleName(Role role) {
        if (role.identifier().getNamespace().equalsIgnoreCase("wathe")) {
            return Text.translatable("announcement.role." + role.identifier().getPath());
        }
        if (!Language.getInstance().hasTranslation("announcement.role." + role.identifier().toTranslationKey()) && Language.getInstance().hasTranslation("announcement.role." + role.identifier().getPath())) {
            return Text.translatable("announcement.role." + role.identifier().getPath());
        }
        return Text.translatable("announcement.role." + role.identifier().toTranslationKey());
    }
}
