package org.agmas.harpymodloader.modded_murder;

import dev.doctor4t.wathe.api.Faction;
import dev.doctor4t.wathe.api.Role;
import dev.doctor4t.wathe.api.WatheRoles;
import dev.doctor4t.wathe.cca.GameWorldComponent;
import dev.doctor4t.wathe.cca.GameRoundEndComponent;
import dev.doctor4t.wathe.cca.ScoreboardRoleSelectorComponent;
import dev.doctor4t.wathe.cca.TrainWorldComponent;
import dev.doctor4t.wathe.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.wathe.game.gamemode.MurderGameMode;
import dev.doctor4t.wathe.util.AnnounceWelcomePayload;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.fabricmc.loader.impl.util.log.Log;
import net.fabricmc.loader.impl.util.log.LogCategory;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.text.MutableText;
import net.minecraft.text.Text;
import net.minecraft.text.Texts;
import net.minecraft.util.Formatting;
import net.minecraft.util.Identifier;
import net.minecraft.world.World;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.agmas.harpymodloader.Harpymodloader;
import org.agmas.harpymodloader.component.WorldModifierComponent;
import org.agmas.harpymodloader.config.HarpyModLoaderConfig;
import org.agmas.harpymodloader.events.ModdedRoleAssigned;
import org.agmas.harpymodloader.events.ModifierAssigned;
import org.agmas.harpymodloader.events.ResetPlayerEvent;
import org.agmas.harpymodloader.modifiers.HMLModifiers;
import org.agmas.harpymodloader.modifiers.Modifier;
import org.jetbrains.annotations.NotNull;

public class ModdedMurderGameMode extends MurderGameMode {

    public ModdedMurderGameMode(Identifier identifier) {
        super(identifier);
    }

    @Override
    public void finalizeGame(ServerWorld serverWorld, GameWorldComponent gameWorldComponent) {
        WorldModifierComponent worldModifierComponent = WorldModifierComponent.KEY.get(serverWorld);
        worldModifierComponent.getModifiers().clear();
        super.finalizeGame(serverWorld, gameWorldComponent);
    }

    @Override
    public void initializeGame(ServerWorld serverWorld, GameWorldComponent gameWorldComponent, List<ServerPlayerEntity> players) {

        Harpymodloader.refreshRoles();

        HarpyModLoaderConfig.HANDLER.load();


        ((TrainWorldComponent)TrainWorldComponent.KEY.get(serverWorld)).setTimeOfDay(TrainWorldComponent.TimeOfDay.NIGHT);
        gameWorldComponent.clearRoleMap();
        for(ServerPlayerEntity player : players) {
            ResetPlayerEvent.EVENT.invoker().resetPlayer(player);
            gameWorldComponent.addRole(player, WatheRoles.CIVILIAN);
        }

        int roleCount = assignVannilaRoles(serverWorld,gameWorldComponent,players);

        assignCivilianReplacingRoles(roleCount,serverWorld,gameWorldComponent,players);

        assignVigilanteReplacingRoles(roleCount,serverWorld,gameWorldComponent,players);

        assignKillerReplacingRoles(roleCount,serverWorld,gameWorldComponent,players);

        /*
         * 左轮必须在所有扩展职业替换结束后再统一发放。
         *
         * 否则像 Better Vigilante 这种“先占用原版义警位、再被扩展职业替换”的角色，
         * 会在替换前就先拿到原版左轮，最终变成“扩展武器 + 左轮”一起出现。
         *
         * 这里统一检查最终职业是否仍然是原版 WatheRoles.VIGILANTE，
         * 只有没被替换掉的普通义警才会获得左轮。
         */
        ScoreboardRoleSelectorComponent.giveRevolversToVanillaVigilantes(gameWorldComponent, players);

        int modifierRoleCount = roleCount * HarpyModLoaderConfig.HANDLER.instance().modifierMultiplier;
        assignModifiers(modifierRoleCount, serverWorld,gameWorldComponent,players);

        for(ServerPlayerEntity player : players) {
            if (Harpymodloader.VANNILA_ROLES.contains(gameWorldComponent.getRole(player))) {
                Role role = gameWorldComponent.getRole(player);
                ServerPlayNetworking.send(player, new AnnounceWelcomePayload(
                        RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(GameRoundEndComponent.getAnnouncementByFaction(role == null ? null : role.getFaction())),
                        roleCount,
                        players.size() - roleCount
                ));
            } else {
                ServerPlayNetworking.send(player, new AnnounceWelcomePayload(RoleAnnouncementTexts.ROLE_ANNOUNCEMENT_TEXTS.indexOf(Harpymodloader.autogeneratedAnnouncements.get(gameWorldComponent.getRole(player))), roleCount, players.size() - roleCount));
            }
        }


        Harpymodloader.FORCED_MODDED_ROLE.clear();
        Harpymodloader.FORCED_MODDED_ROLE_FLIP.clear();

        Harpymodloader.FORCED_MODDED_MODIFIER.clear();
    }

    public void assignModifiers(int desiredRoleCount, ServerWorld serverWorld, GameWorldComponent gameWorldComponent, List<ServerPlayerEntity> players) {
        WorldModifierComponent worldModifierComponent = WorldModifierComponent.KEY.get(serverWorld);
        worldModifierComponent.getModifiers().clear();
        int killerMods = (int) HMLModifiers.MODIFIERS.stream().filter(modifier -> modifier.killerOnly).count();
        HMLModifiers.MODIFIERS.forEach((mod)->{
            int playersAssigned = 0;
            int specificDesiredRoleCount = desiredRoleCount;

            if (mod.killerOnly) {
                specificDesiredRoleCount = (int) Math.floor(Math.floor((double) players.size() / gameWorldComponent.getKillerDividend()) / killerMods);
                specificDesiredRoleCount = Math.max(specificDesiredRoleCount, 1);
            }

            ArrayList<ServerPlayerEntity> shuffledPlayers = new ArrayList<>(players);
            Collections.shuffle(shuffledPlayers);


            if (Harpymodloader.FORCED_MODDED_MODIFIER.containsKey(mod)) {
                for (ServerPlayerEntity player : shuffledPlayers) {
                    if (Harpymodloader.FORCED_MODDED_MODIFIER.get(mod).contains(player.getUuid())) {
                        worldModifierComponent.addModifier(player.getUuid(), mod);
                        ModifierAssigned.EVENT.invoker().assignModifier(player, mod);
                        playersAssigned++;
                    }
                }
            }

            for (ServerPlayerEntity player : shuffledPlayers) {
                if (HarpyModLoaderConfig.HANDLER.instance().disabledModifiers.contains(mod.identifier.toString())) continue;
                if (playersAssigned >= specificDesiredRoleCount) continue;

                if (Harpymodloader.MODIFIER_MAX.containsKey(mod.identifier))
                    if (playersAssigned >= Harpymodloader.MODIFIER_MAX.get(mod.identifier)) continue;

                /*
                 * 词条适用条件统一交给 Modifier#canApplyTo。
                 * 它会先执行旧的静态白名单/黑名单/killerOnly/civilianOnly，
                 * 再执行新增的动态 predicate，方便扩展词条读取 Wathe 公开 API。
                 */
                boolean valid = mod.canApplyTo(gameWorldComponent, player);
                if (!valid) continue;

                if (worldModifierComponent.getModifiers(player) != null && worldModifierComponent.getModifiers(player).size() >= HarpyModLoaderConfig.HANDLER.instance().modifierMaximum)
                    valid = false;

                if (!valid) continue;

                worldModifierComponent.addModifier(player.getUuid(), mod);
                ModifierAssigned.EVENT.invoker().assignModifier(player, mod);
                playersAssigned++;
            }

        });
        for (ServerPlayerEntity player : players) {
            if (!worldModifierComponent.getModifiers(player).isEmpty()) {
                MutableText modifiersText = Text.translatable("announcement.modifier").formatted(Formatting.GRAY)
                        .append(Texts.join(worldModifierComponent.getModifiers(player), Text.literal(", "), modifier -> modifier.getName(false).withColor(modifier.color)));
                player.sendMessage(modifiersText, true);
            } else {
                if (!HMLModifiers.MODIFIERS.isEmpty()) {
                    player.sendMessage(Text.translatable("announcement.no_modifiers").formatted(Formatting.DARK_GRAY), true);
                }
            }
        }
    }

    public void assignCivilianReplacingRoles(int desiredRoleCount, ServerWorld serverWorld, GameWorldComponent gameWorldComponent, List<ServerPlayerEntity> players) {

        // shuffle roles so modded roles are different every time
        ArrayList<Role> shuffledCivillianRoles = new ArrayList<>(WatheRoles.ROLES);
        shuffledCivillianRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !Harpymodloader.isFaction(role, Faction.CIVILIAN));

        ArrayList<Role> shuffledNeutralRoles = new ArrayList<>(WatheRoles.ROLES);
        shuffledNeutralRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !Harpymodloader.isFaction(role, Faction.NEUTRAL));

        ArrayList<ServerPlayerEntity> playersForCivillianRoles = new ArrayList<>(players);
        playersForCivillianRoles.removeIf(player -> {
            Role role = gameWorldComponent.getRole(player);
            return !Harpymodloader.OVERWRITE_ROLES.contains(role) || !Harpymodloader.isFaction(role, Faction.CIVILIAN);
        });

        Collections.shuffle(shuffledCivillianRoles);
        Collections.shuffle(shuffledNeutralRoles);

        int neutralDesiredRoleCount = (int)Math.floor(((float)players.size() / gameWorldComponent.getKillerDividend()));
        int assignedNeutralRoles = 0;
        int neutralRoleCount = 0;

        for (Role role : shuffledNeutralRoles) {
            if (HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().toString())) continue;
            neutralRoleCount++;
        }

        for (Role role : shuffledNeutralRoles) {
            if (HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().toString())) continue;
            /*
             * 这里一定要把“强制职业”和“随机职业名额”拆开看。
             *
             * 原先的逻辑是：
             * 1. 只要随机中立位已经分满，就直接 continue；
             * 2. 于是排在后面的 forced neutral role 根本不会进入 findAndAssignPlayers；
             * 3. 玩家就会保留开局初始化时的 CIVILIAN，表现为 forceRole 中立职业失效。
             *
             * 现在改成：
             * 1. forced role 依旧总能进入 findAndAssignPlayers；
             * 2. 随机补位只吃“剩余中立名额”；
             * 3. 这样无论其他中立职业是否启用，forceRole 指定的中立职业都会稳定生效。
             */
            int remainingNeutralSlots = Math.max(0, neutralDesiredRoleCount - assignedNeutralRoles);
            boolean hasForcedPlayers = hasForcedPlayersForRole(role, playersForCivillianRoles, serverWorld);
            if (remainingNeutralSlots <= 0 && !hasForcedPlayers) continue;

            int roleSpecificDesireCount = Math.min((int) Math.ceil((double) playersForCivillianRoles.size() / neutralRoleCount), desiredRoleCount);
            roleSpecificDesireCount = Math.min(roleSpecificDesireCount, remainingNeutralSlots);
            if (Harpymodloader.ROLE_MAX.containsKey(role.identifier())) roleSpecificDesireCount = Harpymodloader.ROLE_MAX.get(role.identifier());

            assignedNeutralRoles += findAndAssignPlayers(roleSpecificDesireCount, role, playersForCivillianRoles,gameWorldComponent,serverWorld);
            playersForCivillianRoles.removeIf(player -> {
                Role role2 = gameWorldComponent.getRole(player);
                return !Harpymodloader.OVERWRITE_ROLES.contains(role2);
            });
        }

        playersForCivillianRoles.removeIf(player -> {
            Role role = gameWorldComponent.getRole(player);
            return !Harpymodloader.isFaction(role, Faction.CIVILIAN);
        });

        int roleCount= 0;
        for (Role role : shuffledCivillianRoles) {
            if (HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().toString())) continue;
            roleCount++;
        }

        for (Role role : shuffledCivillianRoles) {
            if (HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().toString())) continue;
            int roleSpecificDesireCount = Math.min((int) Math.max(Math.round((double) playersForCivillianRoles.size() / roleCount),1), desiredRoleCount);
            if (Harpymodloader.ROLE_MAX.containsKey(role.identifier())) roleSpecificDesireCount = Harpymodloader.ROLE_MAX.get(role.identifier());

            findAndAssignPlayers(roleSpecificDesireCount, role, playersForCivillianRoles,gameWorldComponent,serverWorld);
            playersForCivillianRoles.removeIf(player -> {
                Role role2 = gameWorldComponent.getRole(player);
                return !Harpymodloader.OVERWRITE_ROLES.contains(role2);
            });
        }
    }

    /**
     * 用扩展义警职业替换原版义警位。
     *
     * <p>这里单独拆一层，而不是继续把义警类职业混进平民池，
     * 是为了让“义警阵营”真正成为独立阵营：
     * 1. 开局欢迎文本按义警阵营显示；
     * 2. 结算时归入义警栏目；
     * 3. 左轮冷却按义警阵营生效；
     * 4. 扩展模组还能按“当前义警位数”决定某个职业是否允许刷新。</p>
     */
    public void assignVigilanteReplacingRoles(int desiredRoleCount, ServerWorld serverWorld, GameWorldComponent gameWorldComponent, List<ServerPlayerEntity> players) {
        ArrayList<Role> shuffledVigilanteRoles = new ArrayList<>(WatheRoles.ROLES);
        shuffledVigilanteRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !Harpymodloader.isFaction(role, Faction.VIGILANTE));

        ArrayList<ServerPlayerEntity> playersForVigilanteRoles = new ArrayList<>(players);
        playersForVigilanteRoles.removeIf(player -> {
            Role role = gameWorldComponent.getRole(player);
            return !Harpymodloader.OVERWRITE_ROLES.contains(role) || !Harpymodloader.isFaction(role, Faction.VIGILANTE);
        });

        Collections.shuffle(shuffledVigilanteRoles);

        int roleCount = 0;
        for (Role role : shuffledVigilanteRoles) {
            if (HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().toString())) continue;
            roleCount++;
        }

        for (Role role : shuffledVigilanteRoles) {
            if (HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().toString())) continue;
            int roleSpecificDesireCount = Math.min((int) Math.max(Math.round((double) playersForVigilanteRoles.size() / Math.max(roleCount, 1)), 1), desiredRoleCount);
            if (Harpymodloader.ROLE_MAX.containsKey(role.identifier())) roleSpecificDesireCount = Harpymodloader.ROLE_MAX.get(role.identifier());

            findAndAssignPlayers(roleSpecificDesireCount, role, playersForVigilanteRoles, gameWorldComponent, serverWorld);
            playersForVigilanteRoles.removeIf(player -> {
                Role role2 = gameWorldComponent.getRole(player);
                return !Harpymodloader.OVERWRITE_ROLES.contains(role2);
            });
        }
    }

    /**
     * 判断当前这一轮待分配玩家里，是否有人被 forceRole 强制指定为了某个职业。
     *
     * <p>这个判断专门服务于“中立职业名额已满但仍有强制中立职业要落地”的场景。
     * 只要队列里还有被强制到该职业的玩家，我们就必须继续让该职业进入分配函数。</p>
     */
    private static boolean hasForcedPlayersForRole(@NotNull Role role, @NotNull List<ServerPlayerEntity> players, @NotNull World world) {
        if (!Harpymodloader.FORCED_MODDED_ROLE.containsKey(role)) {
            return false;
        }
        for (UUID uuid : Harpymodloader.FORCED_MODDED_ROLE.get(role)) {
            PlayerEntity player = world.getPlayerByUuid(uuid);
            if (player instanceof ServerPlayerEntity serverPlayer && players.contains(serverPlayer)) {
                return true;
            }
        }
        return false;
    }




    public void assignKillerReplacingRoles(int desiredRoleCount, ServerWorld serverWorld, GameWorldComponent gameWorldComponent, List<ServerPlayerEntity> players) {

        // shuffle roles so modded roles are different every time
        ArrayList<Role> shuffledKillerRoles = new ArrayList<>(WatheRoles.ROLES);
        shuffledKillerRoles.removeIf(role -> Harpymodloader.VANNILA_ROLES.contains(role) || !Harpymodloader.isFaction(role, Faction.KILLER));

        ArrayList<ServerPlayerEntity> playersForKillerRoles = new ArrayList<>(players);
        playersForKillerRoles.removeIf(player -> {
            Role role = gameWorldComponent.getRole(player);
            return !Harpymodloader.OVERWRITE_ROLES.contains(role) || !Harpymodloader.isFaction(role, Faction.KILLER);
        });

        Collections.shuffle(shuffledKillerRoles);

        int roleCount= 0;
        for (Role role : shuffledKillerRoles) {
            if (HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().toString())) continue;
            roleCount++;
        }
        for (Role role : shuffledKillerRoles) {
            if (HarpyModLoaderConfig.HANDLER.instance().disabled.contains(role.identifier().toString())) continue;
            int roleSpecificDesireCount = Math.min((int) Math.max(Math.round((double) playersForKillerRoles.size() / roleCount),1), desiredRoleCount);
            if (Harpymodloader.ROLE_MAX.containsKey(role.identifier())) roleSpecificDesireCount = Harpymodloader.ROLE_MAX.get(role.identifier());

            findAndAssignPlayers(roleSpecificDesireCount, role, playersForKillerRoles,gameWorldComponent,serverWorld);
            playersForKillerRoles.removeIf(player -> {
                Role role2 = gameWorldComponent.getRole(player);
                return !Harpymodloader.OVERWRITE_ROLES.contains(role2);
            });
        }
    }

    private static int findAndAssignPlayers(int desiredRoleCount, Role role, @NotNull List<ServerPlayerEntity> players, GameWorldComponent gameWorldComponent, World world) {

        ArrayList<ServerPlayerEntity> assignedPlayers = new ArrayList<>();

        if (Harpymodloader.FORCED_MODDED_ROLE.containsKey(role)) {
            for (UUID uuid : Harpymodloader.FORCED_MODDED_ROLE.get(role)) {
                PlayerEntity player = world.getPlayerByUuid(uuid);
                if (player instanceof ServerPlayerEntity serverPlayer) {
                    if (players.contains(serverPlayer)) {
                        assignedPlayers.add(serverPlayer);
                        --desiredRoleCount;
                        ModdedWeights.roleRounds.get(role).put(player.getUuid(), ModdedWeights.roleRounds.get(role).getOrDefault(player.getUuid(), 1) + 1);
                    }
                }
            }
        }

        HashMap<ServerPlayerEntity, Float> map = new HashMap<>();
        float total = 0.0F;

        for(ServerPlayerEntity player : players) {
            if (!Harpymodloader.FORCED_MODDED_ROLE_FLIP.containsKey(player.getUuid()) && Harpymodloader.OVERWRITE_ROLES.contains(gameWorldComponent.getRole(player))) {
                float weight = (float)Math.exp((-ModdedWeights.roleRounds.get(role).getOrDefault(player.getUuid(),1) * 4));
                if (!gameWorldComponent.areWeightsEnabled()) {
                    weight = 1.0F;
                }

                map.put(player, weight);
                total += weight;
            }
        }

        for(int i = 0; i < desiredRoleCount; ++i) {
            float random = world.getRandom().nextFloat() * total;

            for(Map.Entry<ServerPlayerEntity, Float> entry : map.entrySet()) {
                if (!Harpymodloader.FORCED_MODDED_ROLE_FLIP.containsKey(entry.getKey().getUuid()) && Harpymodloader.OVERWRITE_ROLES.contains(gameWorldComponent.getRole(entry.getKey()))) {
                    random -= entry.getValue();
                    if (random <= 0.0F) {
                        assignedPlayers.add(entry.getKey());
                        total -= entry.getValue();
                        map.remove(entry.getKey());
                        ModdedWeights.roleRounds.get(role).put(entry.getKey().getUuid(), ModdedWeights.roleRounds.get(role).getOrDefault(entry.getKey().getUuid(), 1) + 1);
                        break;
                    }
                }
            }
        }

        int i = 0;
        for(ServerPlayerEntity player : assignedPlayers) {
            gameWorldComponent.addRole(player,role);
            Log.info(LogCategory.GENERAL, player.getNameForScoreboard() + " || " + role.identifier());
            ModdedRoleAssigned.EVENT.invoker().assignModdedRole(player,role);
            i++;
        }
        return i;
    }

    public int assignVannilaRoles(ServerWorld serverWorld, GameWorldComponent gameWorldComponent, List<ServerPlayerEntity> players) {
        ScoreboardRoleSelectorComponent roleSelector = ScoreboardRoleSelectorComponent.KEY.get(serverWorld.getScoreboard());

        int killerCount = (int)Math.floor(((float)players.size() / gameWorldComponent.getKillerDividend()));
        int vigilanteCount = (int)Math.floor(((float)players.size() / gameWorldComponent.getVigilanteDividend()));

        List<ServerPlayerEntity> playersForVigilante = new ArrayList<>(players);
        playersForVigilante.removeIf(player -> Harpymodloader.FORCED_MODDED_ROLE_FLIP.containsKey(player.getUuid()));

        List<ServerPlayerEntity> playersForKiller = new ArrayList<>(players);
        playersForKiller.removeIf(player -> {
            if (Harpymodloader.FORCED_MODDED_ROLE_FLIP.containsKey(player.getUuid())) {
                Role forcedRole = Harpymodloader.FORCED_MODDED_ROLE_FLIP.get(player.getUuid());
                /*
                 * forceRole 指到扩展义警职业时，必须先拿到一个“原版义警位”，
                 * 后续 assignVigilanteReplacingRoles 才有机会把这个义警位替换成真正的扩展义警职业。
                 *
                 * 如果这里像以前一样把所有非杀手 forced role 都直接排除，
                 * 那么 Better Vigilante 这类职业既拿不到 vanilla vigilante 位，
                 * 也不在 civilian 替换池里，最终就会掉回 CIVILIAN。
                 */
                if (Harpymodloader.isFaction(forcedRole, Faction.KILLER)) {
                    roleSelector.forcedKillers.add(player.getUuid());
                    return false;
                }
                if (Harpymodloader.isFaction(forcedRole, Faction.VIGILANTE)) {
                    roleSelector.forcedVigilantes.add(player.getUuid());
                    return false;
                }
                return true;
            }
            return false;
        });


        int total = roleSelector.assignKillers(serverWorld, gameWorldComponent, playersForVigilante, killerCount);
        roleSelector.assignVigilantes(serverWorld, gameWorldComponent, playersForKiller, vigilanteCount);
        return total;
    }
}
